byroot/frozen_record

lib/frozen_record/base.rb
spec/frozen_record_spec.rb
spec/spec_helper.rb

This fixes multiple deprecation warnings in test.
```
WARNING: Using the `raise_error` matcher without providing a specific
error or message risks false positives, since `raise_error` will match
when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`,
potentially allowing the expectation to pass without even executing the
method you are intending to call. Instead consider providing a specific
error class or message. This message can be supressed by setting:
`RSpec::Expectations.configuration.warn_about_potential_false_positives
= false`.
```
```
RSpec::Core::Configuration#treat_symbols_as_metadata_keys_with_true_values=
is deprecated, it is now set to true as default and setting it to false
has no effect.
```
```
Using `stub` from rspec-mocks' old `:should` syntax without …
```

Fix deprecation warnings in tests

---

lib/frozen_record/base.rb
spec/fixtures/countries.yml
spec/frozen_record_spec.rb

Adds support for pre-processing the yml file using ERB. 
This is consistent with the way Rails already treats many yml files. I have a specific use case that would benefit from this where I have frozen records with json templates and I'd prefer to store the json in individual files and keep my yml file easier to work with. Thus I need to read files using ruby in my frozen record yml file.
@byroot

add support for erb in frozen record yml files

---

spec/scope_spec.rb

https://github.com/byroot/frozen_record/pull/18 has a broken test. It looks like Ruby 2.4 fixed a precision bug when summing floats, so I'm fixing the test.
We just have to remember to remove the delta once we no longer care about other versions of Ruby.
cc @davidcornu

Assert sum within a delta

---

lib/frozen_record/scope.rb
spec/scope_spec.rb
spec/support/country.rb

We have a model with a complex sorting strategy that can't be implemented with simple attributes. This PR will allow instance methods to be used as sorting keys, so we can implement the sorting strategy in the class itself.
cc @davidcornu

Compare using send instead of []

---

lib/frozen_record/base.rb

This changes the behaviour of eager_load! to no-op if auto_reloading is true. This allows for an exception-free eager_loading experience in development mode if you ever eager_load all of your namespaces.

Don't raise on eager_load! when auto_reloading is true

---

.gitignore
lib/frozen_record/test_helper.rb
spec/fixtures/test_helper/countries.yml
spec/spec_helper.rb
spec/test_helper_spec.rb

Splitting out a test helper added in https://github.com/Shopify/shopify/pull/185768 to be included in the upstream gem. 
```ruby
require 'frozen_record/test_helper'
test_fixtures_base_path = 'alternate/fixture/path'
FrozenRecord::TestHelper.load_fixture(Country, test_fixtures_base_path)
FrozenRecord::TestHelper.unload_fixtures
```

Introduce FrozenRecord::TestHelper.load_fixture and .unload_fixtures

---

lib/frozen_record/test_helper.rb
spec/test_helper_spec.rb

My last-minute changes to https://github.com/byroot/frozen_record/pull/23 overlooked the scenario in which `unload_fixtures` is called on its own, when `load_fixture` has either never been called prior, or was already called. `@cache` is nil or undefined this situation, so we error out trying to call `.each`.
This PR fixes that problem.

Fix TestHelper.unload_fixtures when run on its own

---

README.md
lib/frozen_record/base.rb
spec/fixtures/countries.yml
spec/frozen_record_spec.rb

Originally when I tried to fix the issue of comparing scopes, I tried to give scopes a name attribute. To automatically set the name, I ended up using a simplified version of the scope method from https://github.com/rails/rails/blob/master/activerecord/lib/active_record/scoping/named.rb. 
Giving a scope a name didn't work because what happens when you chain them? A big ugly mess is what. I think #27 is a better solution for comparing scopes.  
The simplified scope method still seemed like it might be some nice, so I thought I'd make a PR for that too while I was at it.

add scope :symbol, lamda syntax

---

lib/frozen_record/scope.rb
spec/fixtures/countries.yml
spec/scope_spec.rb
spec/support/country.rb

This PR adds 2 new public methods and one protected method to allow different instances of Scope to be compared. This addresses the issue we had in this PR https://github.com/Shopify/shopify/pull/211784#issuecomment-521268785 
When two instances of Scope have the same have the same unique and sorted `@where_values` and `@where_not_values` and the same unique (but unsorted) `@order_values`, then they could be considered the same scope. 
I also added `nato: true` to the France fixture just because France is part of NATO 😄

add equality operator to compare two scopes

---

README.md
lib/frozen_record/backends.rb
lib/frozen_record/backends/json.rb
lib/frozen_record/base.rb
spec/support/animal.rb

This builds atop of the work done in https://github.com/byroot/frozen_record/pull/20 and makes it easier to share FrozenRecord data files between backend gems and frontend modules (something I'd like for https://github.com/activemerchant/payment_icons for example) without everyone needing to reimplement the Ruby JSON backend in their app.

Include JSON backend by default

---

lib/frozen_record/scope.rb
spec/scope_spec.rb
spec/support/country.rb

Chaining a scope class method with Ruby 2.7+ and keyword args fails without this patch. [Example from Shopify](https://github.com/Shopify/shopify/pull/265075/files#diff-e18916e0bcf75f7ace2a36dbeb598b654b6ea48b19a362f3e99891908af81c49R51). 
@byroot 's original suggestion was to try `ruby2_keywords :delegate_to_class if respond_to?(:ruby2_keywords, true)` for the method below, but I found that I could only get tests to pass (like [this one](https://github.com/Shopify/shopify/pull/265075/files#diff-c16ae735612081f6ae06a57350ad95e2f39f7f467efdcf201f1d15b72ab9eb9bR66)) if I targeted `method_missing` instead.

Fix Ruby 2.7 kwargs usage in chained scoped methods

---

lib/frozen_record.rb

This PR replaces `require 'active_support/all'` with the minimal subset of core extensions necessary to keep the tests passing. This allows performance-sensitive consumers to avoid core extensions they don't need.

Require a minimal subset of ActiveSupport

---

lib/frozen_record/base.rb
lib/frozen_record/compact.rb
lib/frozen_record/scope.rb

Hey, sorry I didn't catch this one earlier.
When we require only `frozen_record/minimal` these calls to `Set#exclude?` fail.  So this PR replaces `exclude?` with `!(...).include?`.
Another approach would be to explicitly require `active_support/core_ext/enumerable`. That would impose that requirement on consumers, but from my reading it's not too heavy of a module. Happy to go either way.

Change exclude? calls to lessen dependency on active_support

---

.github/workflows/main.yml
spec/scope_spec.rb
spec/spec_helper.rb

This adds a dimension to the CI matrix to run the test suite with only `frozen_record/minimal` required. When testing the minimal configuration, it skips tests tagged with `exclude_minimal`.

Add a dimension of the CI matrix to test frozen_record/minimal

---

spec/spec_helper.rb

I should have made https://github.com/byroot/frozen_record/pull/43 a draft PR first, sorry.
Turns out that Github writes booleans to the env as strings, which means the exclude_minimal tests were always excluded.
Now we check the value rather than just the truthiness.

Check value of MINIMAL env variable because github sets it "false"

---

lib/frozen_record/backends/yaml.rb

With 4.0 psych now defaults `YAML.load` to `YAML.safe_load`, which needs you to specify the classes you allow via the permitted_classes option [here](https://github.com/ruby/psych/blob/216f94fb9aacb0754f1dd2257b8d6a61b278a8b2/lib/psych.rb#L322).
Without permitted classes specified, loading Dates of Regexp for example, produces an error:
https://github.com/ruby/psych/issues/496
https://github.com/ruby/psych/issues/489
Similar to what was done with ActiveRecord with [Rails 6.1.4](https://github.com/rails/rails/releases/tag/v6.1.4), should FrozenRecord switch to loading YAML backends using `unsafe_load` to be compatible with psych 4?
I believe the yaml files would be considered "[trusted sources](https://github.com/ruby/psych/issues/489#issuecomment-841354484)", as they are in-repo.
I have …

if defined use unsafe_load and unsafe_load_file for YAML backends [support psych >= 4.0]

---

README.md

👋  Ran into a `no implicit conversion of Array into String` error with the default testing example. Looks like we need to splat the array of strings so we have `join('test', 'support', 'fixtures')` instead of `join(['test', 'support', 'fixtures'])`.
Mild 🎩 🎩 🎩 🎩 🎩 
CC @tzyinc

Fix README testing example

---

lib/frozen_record/test_helper.rb
spec/fixtures/continents.yml.erb
spec/fixtures/test_helper/continents.yml.erb
spec/support/continent.rb
spec/test_helper_spec.rb

This PR introduces the ability to unload fixtures for a specific class.
In our applications' test suites, we've often found ourselves wanting to load one set of general fixtures to back our models for most tests, but then to load several different, more specific fixtures just for each model's unit tests. The inability to unload fixtures for a single class made this very difficult.

Granular fixture unloads

---

lib/frozen_record.rb

As pointed by the [Rails documentation](https://api.rubyonrails.org/classes/Rails/Railtie.html#class-Rails::Railtie-label-Creating+a+Railtie), creating Railties should explicitly ensure that `Rails::Railtie` is defined.
There could be non-rails application use-cases where `Rails` is defined, yet `Rails::Railtie` is not loaded.
I'm not sure how to add a test for this, if you have any idea?

Only load `Railtie` integration if `Rails::Railtie` is defined

---

CHANGELOG.md
lib/frozen_record/base.rb
spec/frozen_record_spec.rb

The implementation in this commit brings `FrozenRecord::Base#==` in
line with [`ActiveRecord::Base#==`](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/core.rb#L557).
It fixes a bug where records without IDs would evaluate as equal to
each other. This behaviour was unintuitive and misaligned with the
(better) `ActiveRecord::Base` implementation.

`#==` returns `false` if primary key is `nil`

---

README.md
lib/frozen_record/base.rb
lib/frozen_record/compact.rb
spec/fixtures/countries.yml.erb
spec/frozen_record_spec.rb
spec/support/country.rb

This PR  adds an `attribute` method for providing a custom attribute deserialization class
The `attribute` method takes a field name and a class.  The class must provide a `load` class method that takes 
the attribute value from the file and returns a deserialized version.  ([Similar to ActiveRecord's serialize](https://api.rubyonrails.org/v7.0.4/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html#method-i-serialize))
Deserialization is performed in the code close to where default field values are set, as this seemed like a roughly similar operation to me.
This change removes the need to manually serialize and deserialize, for example, Sorbet T::Enums, when using FrozenRecords
```ruby
class AnimalEnum < T::Enum
def self.load(value)
try_deserialize(value)
end
enums do
Dog …
```

Add Custom Attribute De-serialization

---

lib/frozen_record/test_helper.rb
spec/fixtures/test_helper/only_in_tests.yml.erb
spec/test_helper_spec.rb

When using the test helper with fixtures that only exist under their name in tests, then `unload_fixture` was bailing as it tried to force load those model classes from their "original" path.
Just rescue from any StandardError (load records throws Errno::ENOENT) on `load_records` in the `unload_fixture` implementation. 
Leaving all test frozenrecords with names that also exist in the normal path and splitting them by different path names.
That was a bit unwieldy to have so many directories names like tests which all contained the same file name.
- Is their another way to do that and not blowing up the path structure for multiple fixtures?
- Should we log maybe?
- Should I catch the ` Errno::ENOENT` specifically?

Handle gracefully fixtures that only exist for tests in `TestHelper.unload_fixture`
